name: flutter_config
description: Plugin that exposes environment variables to your Dart code in Flutter as well as to your native code in iOS and Android. Bring some 12 factor love to your Flutter apps
version: 1.0.5
author: Edgar <edgar@byneapp.com>
homepage: https://github.com/ByneappLLC/flutter_config

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.byneapp.flutter_config
    pluginClass: FlutterConfigPlugin
